In [1]:
import pandas as pd
import datetime as dt
from datetime import datetime
import seaborn as sns

In [8]:
#Read in player logs
hist_player_log_full = pd.read_csv('hist_player_log.csv')
hist_player_log_full['GAME_DATE'] = hist_player_log_full['GAME_DATE'].apply(lambda x: datetime.strptime(x, '%b %d, %Y'))
#Read in player injury history
full_injury_data_final = pd.read_csv('full_injury_data_final.csv', parse_dates=['Date'])
#Read in player info
hist_player_info = pd.read_csv('hist_player_info.csv', parse_dates=['BIRTHDATE'])

In [12]:
#Build a dataset for effect analysis.
full_injury_data_final.head()

,Date,Team,Acquired,Relinquished,Notes,full_name_raw,full_name_main,full_name_alt,full_name_brack,injury_class,...,injury_position_lower,injury_surgery,injury_strained,injury_sprained,injury_sore,injury_details,injury_anat,injury_anat_partone,full_name,_merge
0,2014-05-03,Warriors,,Andrew Bogut,fractured right rib (DNP),Andrew Bogut,Andrew Bogut,NaN,NaN,DNP,...,0,0,0,0,0,fractured rib,rib,rib,NaN,left_only
1,2014-05-04,Mavericks,,Gal Mekel,knee injury (DNP),Gal Mekel,Gal Mekel,NaN,NaN,DNP,...,0,0,0,0,0,knee,knee,knee,NaN,left_only
2,2014-05-06,76ers,,Michael Carter-Williams,surgery on right shoulder to repair torn labru...,Michael Carter-Williams,Michael Carter-Williams,NaN,NaN,out indefinitely,...,0,1,0,0,0,shoulder repair torn labrum,shoulder repair labrum,shoulder,NaN,left_only
3,2014-05-13,Cavaliers,,Anthony Bennett,surgery for removal of tonsils and adnoids (ou...,Anthony Bennett,Anthony Bennett,NaN,NaN,out indefinitely,...,0,1,0,0,0,removal tonsils adnoids,removal tonsils adnoids,removal,NaN,left_only
4,2014-05-14,Blazers,,Maurice Williams / Mo Williams,strained groin (DNP),Maurice Williams / Mo Williams,Maurice Williams,Mo Williams,NaN,DNP,...,0,0,1,0,0,strained groin,groin,groin,NaN,left_only

In [10]:
hist_player_log_full[['full_name', 'GAME_DATE', 'MIN']].head()

      full_name  GAME_DATE  MIN
0  Alex Abrines 2018-12-23   27
1  Alex Abrines 2018-12-22   16
2  Alex Abrines 2018-12-19   23
3  Alex Abrines 2018-12-17   14
4  Alex Abrines 2018-12-15   20